name: Atualizar Ações Diariamente
on:
  schedule:
    - cron: '0 23 * * *'  # 20h BRT (23h UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y python3-dev libxml2-dev libxslt-dev

      - name: Executar script com delays
        run: |
          # Executa em lotes com delays maiores
          python script_investbr.py --batch-size=20 --delay=15
          # Ou para teste com poucas ações:
          # python script_investbr.py --test-mode

      - name: Commit e push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dados_acoes.json
          if git diff --staged --quiet; then
            echo "Nenhuma alteração detectada"
          else
            git commit -m "Atualização automática $(date -u +'%d/%m/%Y %H:%M UTC')"
            git push origin main
          fi