name: Atualizar Ações Diariamente
on:
  schedule:
    - cron: '0 23 * * *'  # 20h BRT (23h UTC)
  workflow_dispatch:  # Permite acionar manualmente

permissions:  # Permissões explícitas
  contents: write  # Permite push no repositório

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante o histórico completo do Git

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: python script_investbr.py  # Executa o script principal

      - name: Commit e push atualizações
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add dados_acoes.json
          if git diff --staged --quiet; then
            echo "Nenhuma alteração detectada"
          else
            git commit -m "Atualização automática $(date -u +'%d/%m/%Y %H:%M UTC')"
            git push origin main
          fi