name: Atualizar Ações Diariamente
on:
  schedule:
    - cron: '0 23 * * *'  # 20h no horário de Brasília (UTC-3)
  workflow_dispatch:  # Permite acionar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python script_investbr.py
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dados_acoes.json
          git commit -m "Atualização automática $(date +'%d/%m/%Y %H:%M')"
          git push